<?php
$config['dbhost']='localhost';
$config['dbuser']='';
$config['dbpass']='';
$config['dbname']='';
$config['basepath']='';
$config['controller']='main';
$config['host']='';
$config['title']='';
$config['meta']='';
$config['development']=0;
