<?php
$config['dbhost']='localhost';
$config['dbuser']='';
$config['dbpass']='';
$config['dbname']='';
$config['basepath']='/var/www/framework/app';
$config['home']='home';
$config['host']='';
$config['title']='';
$config['meta']='';
$config['development']=1;
